apiVersion: v1
kind: Namespace
metadata:
  name: healthcare-ai-production
  labels:
    environment: production
    app.kubernetes.io/name: healthcare-ai
    app.kubernetes.io/environment: production

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-network-policy
  namespace: healthcare-ai-production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          environment: production
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          environment: production
    - podSelector: {}
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: production-secrets
  namespace: healthcare-ai-production
  annotations:
    description: "PRODUCTION SECRETS - MUST BE UPDATED WITH SECURE VALUES"
type: Opaque
data:
  # IMPORTANT: These are placeholder values - MUST be updated with secure production secrets
  # Example: echo -n 'secure-production-password' | base64
  postgres_password: PLEASE_UPDATE_PRODUCTION_POSTGRES_PASSWORD_BASE64
  minio_password: PLEASE_UPDATE_PRODUCTION_MINIO_PASSWORD_BASE64  
  grafana_password: PLEASE_UPDATE_PRODUCTION_GRAFANA_PASSWORD_BASE64