global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Model Registry Service
  - job_name: 'model-registry'
    static_configs:
      - targets: ['model-registry:8000']
    metrics_path: /metrics
    scrape_interval: 15s

  # Feature Store Service
  - job_name: 'feature-store'
    static_configs:
      - targets: ['feature-store:8002']
    metrics_path: /metrics
    scrape_interval: 15s

  # Experiment Tracking Service
  - job_name: 'experiment-tracking'
    static_configs:
      - targets: ['experiment-tracking:8003']
    metrics_path: /metrics
    scrape_interval: 15s

  # Pipeline Orchestrator Service
  - job_name: 'pipeline-orchestrator'
    static_configs:
      - targets: ['pipeline-orchestrator:8004']
    metrics_path: /metrics
    scrape_interval: 15s

  # A/B Testing Service
  - job_name: 'ab-testing'
    static_configs:
      - targets: ['ab-testing:8090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Infrastructure services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093