# IMPORTANT: Secret management for MinIO credentials
# This file previously contained hardcoded base64-encoded secrets which have been removed for security.
# 
# Please use external secret management solutions such as:
# - Kubernetes Secrets Store CSI Driver
# - HashiCorp Vault
# - AWS Secrets Manager
# - Azure Key Vault
# - Google Secret Manager
# - Sealed Secrets
#
# The deployment expects a Secret named 'minio-secret' with the following keys:
# - username: MinIO root username
# - password: MinIO root password
#
# Example using external-secrets operator:
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: minio-secret
#   namespace: healthcare-ai-staging
# spec:
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: minio-secret
#   data:
#   - secretKey: username
#     remoteRef:
#       key: staging/minio
#       property: username
#   - secretKey: password
#     remoteRef:
#       key: staging/minio
#       property: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: healthcare-ai-staging
  labels:
    app: minio
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        ports:
        - containerPort: 9000
        - containerPort: 9001
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address ":9001"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: username
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: password
        volumeMounts:
        - name: minio-storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: healthcare-ai-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: healthcare-ai-staging
  labels:
    app: minio
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: healthcare-ai-staging
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    nodePort: 31000
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 31001
  selector:
    app: minio