apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: healthcare-ai-dev
type: Opaque
stringData:
  # These values should be provided via sealed secrets or external secret management
  # Never commit actual values to version control
  username: POSTGRES_USER_PLACEHOLDER
  password: POSTGRES_PASSWORD_PLACEHOLDER
  database: POSTGRES_DB_PLACEHOLDER
---
# Instructions for creating secrets:
# 
# Option 1: Using kubectl with environment variables
# kubectl create secret generic postgres-secret \
#   --from-literal=username=$POSTGRES_USER \
#   --from-literal=password=$POSTGRES_PASSWORD \
#   --from-literal=database=$POSTGRES_DB \
#   -n healthcare-ai-dev
#
# Option 2: Using Sealed Secrets (recommended for GitOps)
# 1. Install sealed-secrets controller
# 2. Create secret: kubectl create secret generic postgres-secret --dry-run=client -o yaml | kubeseal -o yaml > postgres-secret-sealed.yaml
#
# Option 3: Using External Secrets Operator with HashiCorp Vault
# See documentation for external-secrets configuration